apache_primitives = {
    "INT32": "int",
    "FLOAT32": "float",
    "STRING": "string",
    "BIGINT": "biginteger",
    "FLOAT": "float",
    "FLOAT_1": "float",
    "INTEGER": "long",
    "VARCHAR": "string",
    "DOUBLE": "double",
    "DECIMAL": "bigdecimal",
    "TIMESTAMP": "date",
    "TIMESTAMPTZ": "date",
    "DATE": "date",
    "DATETIME": "date",
    "CHAR": "byte",
    "BOOLEAN": "boolean",
    "VARBINARY": "string",
    "JSON": "string",
    "LIST": "string",
    "MAP": "string"
}
